export * from './createQuestion.component';
export * from './listQuestions.component';
export * from './deleteQuestion.component';
export * from './editQuestion.component';
export * from './manageQuestion.component';
export * from './createMCQ.component';
export * from './createOQ.component';
export * from './listMCQ.component';
export * from './listOQ.component';
